apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deploy
  namespace: ctse-microservices
  labels:
    app: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: dinalsenadheera/ctse-assignment-as:latest
          ports:
            - containerPort: 3010
          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: auth-mongo-uri
            - name: PORT
              value: '3010'
            - name: NODE_ENV
              value: 'production'
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: ctse-microservices
spec:
  type: ClusterIP
  selector:
    app: auth
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3010
